# Generated by Django 4.2.23 on 2025-08-13 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=255, verbose_name='نوع عملیات')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='زمان عملیات')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='جزئیات تغییرات')),
                ('who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش تغییرات',
                'verbose_name_plural': 'گزارش\u200cهای تغییرات',
                'ordering': ['-when'],
            },
        ),
    ]
