# Generated by Django 5.2.5 on 2025-08-14 16:17

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('legal_name', models.CharField(max_length=255, unique=True, verbose_name='نام/عنوان حقوقی سازمان/شرکت/فروشگاه')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='نام تجاری (برند)')),
                ('registration_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه ملی / کد اقتصادی')),
                ('country', models.CharField(default='Iran', max_length=100, verbose_name='کشور')),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='استان/ایالت')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='آدرس - سطر ۱')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='آدرس - سطر ۲')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='کدپستی')),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='شماره تلفن نامعتبر است.', regex='^\\+?[0-9\\-\\s]{7,20}$')], verbose_name='تلفن تماس')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('timezone', models.CharField(default='Asia/Tehran', max_length=64, verbose_name='منطقه زمانی (IANA)')),
                ('currency_code', models.CharField(default='IRR', max_length=3, validators=[django.core.validators.RegexValidator(message='کد واحد پول باید سه حرف بزرگ انگلیسی (ISO-4217) باشد.', regex='^[A-Z]{3}$')], verbose_name='کد واحد پول (ISO-4217)')),
                ('extra_settings', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات اضافه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان\u200cها',
                'db_table': 'organizations',
                'ordering': ['legal_name'],
                'indexes': [models.Index(fields=['legal_name'], name='org_legal_name_idx'), models.Index(fields=['is_active'], name='org_active_idx')],
            },
        ),
    ]
